export const translatableStrings = [
  "Built for rural India",
  "Medical advice, explained simply.",
  "In the language you speak.",
  "Prescriptions and diagnoses are written for doctors, not patients. Our assistant turns confusing medical text into plain language, then translates it into your regional language — so every patient understands their own care.",
  "Try it now",
  "See how it works",
  "What the assistant does",
  "Plain-language simplification",
  "Complex diagnoses and prescriptions are rewritten in everyday words, with every medical term explained.",
  "Regional language translation",
  "Simplified explanations are translated into Hindi, Marathi, Tamil, Telugu, Kannada, and more.",
  "Prescription scanning",
  "Photograph or upload a prescription and let the assistant read and process it automatically.",
  "Personal medical history",
  "Every simplified, translated record is saved to your profile, so you can revisit past visits anytime.",
  "How it works",
  "Upload your prescription",
  "Take a photo or upload a PDF of your prescription or medical report.",
  "We simplify the medical text",
  "Our model rewrites the jargon into clear, everyday language.",
  "Choose your language",
  "Select your regional language for the translated explanation.",
  "Read and understand",
  "View your simplified, translated report — and keep it saved for later.",
  "Frequently asked questions",
  "Is my medical information kept private?",
  "Yes. Your prescriptions and reports are only used to generate your simplified, translated summary and are not shared with anyone else.",
  "Which languages are supported?",
  "We use a translation model (NLLB-200) that supports over 200 languages, including all major Indian regional languages. At launch, we're focusing on Hindi, Marathi, Tamil, Telugu, and Kannada, with more regional languages available as we expand.",
  "Do I need internet access to use this?",
  "Yes, an internet connection is currently required to process and translate your documents.",
  "Can a health worker use this on behalf of a patient?",
  "Yes. ASHA workers and clinic staff can upload documents and share the simplified explanation with patients directly.",
  "Get in touch",
  "Questions about the assistant, partnerships with rural clinics, or feedback on the prototype — we'd like to hear from you.",
  "Send message",
  "Thanks for reaching out — we'll get back to you soon.",
  "Health, Explained",
  "An AI healthcare assistant for rural communities.",
];